class User(object):
    email_full = "test@test.com"
    password = "1234"
    autocomplete= "new y"
    option3= "3"
    textArea= "texto texto texto texto texto texto"
    file_input="C:/Users/silvi/OneDrive/Imagens/funciona_minha_maquina.PNG"
    email_empty = ""
    email_part1 = "test"
    email_part2 = "@gmail.com"
    email_mandatory="Email obrigatório"
    success= "Sucesso"
    form_message = "Este é um formulário de exemplo utilizado nos nossos cursos de automação web"